#!/bin/bash

parent_dir=$(dirname "$(pwd)")
html_files=$(find . -maxdepth 1 -type f -name "*.html")

for file in $html_files; do
    filename=$(basename "$file")
    if [[ ! -e "$parent_dir/$filename" || "$file" -nt "$parent_dir/$filename" ]]; then
        cp "$file" "$parent_dir/$filename"
        echo "Copied $file to $parent_dir/$filename"
    fi
done

